post_install() {
    echo "Enabling basic networking with systemd-networkd..."
    systemctl enable --now systemd-resolved systemd-networkd

    echo "Enabling NTP clock synchronization with systemd-timesyncd..."
    systemctl enable --now systemd-timesyncd
    timedatectl set-ntp true

    echo "Enabling home directory management with systemd-homed..."
    systemctl enable --now systemd-homed

    echo "Enabling PCSC socket for GPG cards..."
    systemctl enable --now pcscd.socket

    echo "Enabling wireless and bluetooth daemons..."
    systemctl enable --now iwd bluetooth

    echo "Enabling systemd stub resolv.conf..."
    ln -sf "/run/systemd/resolve/stub-resolv.conf" "/etc/resolv.conf"

    post_upgrade
}

post_upgrade() {
    echo "Reloading network configuration..."
    networkctl reload
}
