post_install() {
    echo "Enabling basic networking with systemd-networkd..."
    systemctl enable --now systemd-resolved
    systemctl enable --now systemd-networkd

    echo "Enabling NTP clock synchronization with systemd-timesyncd..."
    systemctl enable --now systemd-timesyncd
    timedatectl set-ntp true

    echo "Enabling PCSC socket for GPG cards..."
    systemctl enable --now pcscd.socket

    echo "Enabling systemd stub resolv.conf..."
    ln -sf "/run/systemd/resolve/stub-resolv.conf" "/etc/resolv.conf"

    post_upgrade
}

post_upgrade() {
    echo "Reloading network configuration..."
    networkctl reload
}
