post_install() {
    echo "Enabling basic networking with systemd-networkd..."
    systemctl enable --now systemd-resolved
    systemctl enable --now systemd-networkd
    echo "Enabling PCSC socket for GPG cards..."
    systemctl enable --now pcscd.socket
    echo "Enabling KMSCON on all virtual terminals..."
    ln -sf "/usr/lib/systemd/system/kmsconvt@.service" "/etc/systemd/system/autovt@.service"
    echo "Enabling systemd stub resolv.conf..."
    ln -sf "/run/systemd/resolve/stub-resolv.conf" "/etc/resolv.conf"
    post_upgrade
}

post_upgrade() {
    echo "Reloading network configuration..."
    networkctl reload
}

post_remove() {
    rm -f "/etc/systemd/system/autovt@.service"
}
