# A folder where PIMSync can store some metadata about each pair.
status_path ~/.local/share/pimsync/status/

# CardDAV configuration.
storage contacts_local {
    type vdir/vcard
    path ~/.local/share/pimsync/contacts/
    fileext vcf
}

storage contacts_remote {
    type carddav
    url https://dav.example.com/contacts/
    username example@example.com
    password {
        cmd secret-tool lookup hostname dav.example.com username example@example.com
    }
}

pair contacts {
    storage_a contacts_local
    storage_b contacts_remote
    collections all
}

# CalDAV configuration.
storage calendars_local {
    type vdir/icalendar
    path ~/.local/share/pimsync/calendars/
    fileext ics
}

storage calendars_remote {
    type caldav
    url https://dav.example.com/calendar/
    username example@example.com
    password {
        cmd secret-tool lookup hostname dav.example.com username example@example.com
    }
}

pair calendars {
    storage_a calendars_local
    storage_b calendars_remote
    collections all
}
