[start]
# Default home view.
visual-home = "cgi-bin:chabookmark?action=view"

[buffer]
# Enable image display by default.
images = true

# Enable cookie storage for all sites.
cookie = true

[external]
# Default path for downloads.
download-dir = "~/Downloads"

# Copy-paste for Wayland.
copy-cmd  = "wl-copy"
paste-cmd = "wl-paste"

# Keybindings.
[page]
"o"   = "loadCursor"
"O"   = "load"
"C-o" = "prevBuffer"
"C-i" = "nextBuffer"
'C-k' = '() => pager.load("kagi:")'

[line]
"C-j" = "line.prevHist"
"C-k" = "line.nextHist"
"Esc" = "line.cancel"

# Search with Kagi.
[[omnirule]]
match          = "^kagi:"
substitute-url = '(x) => "https://kagi.com/html/search?q=" + encodeURIComponent(x.slice(x.indexOf(":") + 1))'

# Site configuration.
[[siteconf]]
host   = '(www\.)?kagi\.com'
cookie = "save"

